### ISSUE TITLE
User Review

### ISSUE THREAD

**Issue by edavidj** [OpenLiberty/draft-guide-okd#14]
Functional Issues:
- [ ] When using a new minishift instance (v1.33 not v1.34) I was unable to docker login to the registry. This issue was fixed by running `minishift docker-env` followed by `eval $(minishift docker-env)`. 

Preferences/Ease of use:
- [x] Can get rid of warning from `docker login` by running
```sh
echo $(oc whoami -t) | docker login -u developer --password-stdin $(oc registry info)
```
- [x] It's better practice (and looks cooler) to use `$(<command>)` instead of ``` `<command>` ```.
- [ ] To give a direct copy paste for the curl commands when testing routes can use: `curl http://$(oc get route system-route -o jsonpath="{ .spec.host }")/system/properties` but it's a little ugly so might be better to leave as is.

**Comment by MaiHameed** [comment]
> To give a direct copy paste for the curl commands when testing routes can use: curl http://$(oc get route system-route -o jsonpath="{ .spec.host }")/system/properties but it's a little ugly so might be better to leave as is.

We usually avoid this so that the commands are more intuitive in a learning environment.

**Comment by MaiHameed** [comment]
> When using a new minishift instance (v1.33 not v1.34) I was unable to docker login to the registry. This issue was fixed by running minishift docker-env followed by eval $(minishift docker-env).

Will be addressed with a PR

**Comment by MaiHameed** [comment]
Closing since the final change is already requested in the SME review.
