### ISSUE TITLE
paragraph about tar.gz needs to be removed/modified

### ISSUE THREAD

**Issue by NimG98** [OpenLiberty/draft-guide-okd#15]
- [ ] `tar.gz` is not being created anymore with the new ideal pom. This paragraph is either not needed or needs to be reworked to better explain what happens when you package
    > The resulting compiled code will be packaged into a `tar.gz` archive which can be found at `system/target/system.tar.gz`. The archive contains all the configuration files, as well as the application needed to run the microservice on an Open Liberty server, and is now ready to be injected into a Docker container for deployment.

**Comment by MaiHameed** [comment]
Fixed, closing
