### ISSUE TITLE
Dev content review feedback

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-okd#4]
- [x] Spell out OKD in the description
- **What you’ll learn**
  - [x] "... pipeline, it also ... " -> "...  pipeline. It also ..."
- **Starting Minishift**
  - [x] why the export content from `oc-env` are same in 3 platforms?
    - expect Win is different
- [x] Restructure the "Deploying the system microservice" section by promoting the sub sections as main sections as following:
  - Building the system microservice
  - Containerizing the system microservice
    - Re-using the Docker daemon
    - Building the Docker image
    - Accessing the internal registry
  - Deploying the system microservice
- **Deploying the system microservice**
  - **Deploying the microservice**
    - [x] "Now that your Docker images are built, deploy them ..." > "Now that the system Docker image is built, deploy it... "
    - [x] After create the deploy.yaml, does need to run something against it? OR should simpify the create and the 1st update deploy.yaml? e.g. provide the deploy.yaml and just ask readers to update
- **Deploying the inventory microservice**
  - **Containerizing the microservice**
    - [x] Expect the command `docker tag inventory...` for Win should be different
    - [x] The `docker tag inventory...` command not clear that have several `/`. Can they be separated by newlines?
  - **Deploying the microservice**  
    - [x] May need an output sample of `oc get route inventory-route`
- **Testing the microservices**
  - [x] The `mvn verify ...` command no need to have `\` characters. One line should be fine
- [x] Missing `== Great work! You're done!` section?
- [x] "Where to next?" can show the OpenShift guide, Istio guide, Istio FT guide.

**Comment by gkwan-ibm** [comment]
- **Starting Minishift**
  - [ ] in the export content from `oc-env` for Win,  change the name `MaiHameed` to any common name
- [ ] Restructure the "Deploying the system microservice" section by promoting the sub sections as main sections as following (the structure in lgdev is not what I mean):
  - Building the system microservice
  - Containerizing the system microservice
    - Re-using the Docker daemon
    - Building the Docker image
    - Accessing the internal registry
  - Deploying the system microservice
  - Deploying the inventory microservice
      - Building the microservice
      - Containerizing the microservice
     -  Deploying the microservice

**Comment by MaiHameed** [comment]
Addressed with https://github.com/OpenLiberty/draft-guide-okd/pull/5, closing.
